AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auth-resources
  SAM Template for auth resources
Globals:
  Function:
    Timeout: 3

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CustomizeUnicorn-users
      AutoVerifiedAttributes:
        - email
  CongintoUserPoolGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Admin user group to manage partners
      GroupName: admin
      UserPoolId: !Ref CognitoUserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: admin-client
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

  UserPoolSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /serverless-security-workshop/auth/user-pool-id
      Value: !Ref CognitoUserPool

  UserPoolARNSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /serverless-security-workshop/auth/user-pool-arn
      Value: !GetAtt CognitoUserPool.Arn

  UserPoolAppClientSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /serverless-security-workshop/auth/user-pool-client-id
      Value: !Ref UserPoolClient

Outputs:
  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool

  CognitoAppClientId:
    Description: "Cognito App Client ID"
    Value: !Ref UserPoolClient

  UserPoolARNSSM:
    Description: "UserPool ID"
    Value: !Ref UserPoolARNSSM